### ISSUE TITLE
Feature Request - Ability to start and stop cars engine

### ISSUE THREAD

**Issue by Archemedees** [samrum/homebridge-onstar#15]
I absolutely love this integration. The only thing it is missing in my opinion is the ability to start my car or stop it. Then I could automate my morning routine completely. Is this something that can be added?

**Comment by TravelinMax** [comment]
The "Car climate" switch starts your car. I don't think there's a way to stop it though.

**Comment by samrum** [comment]
> The "Car climate" switch starts your car. I don't think there's a way to stop it though.

Right “Car Climate” is remote start or precondition or what have you.

There’s not a way to turn it off with the switch, but you can use Siri to do it with “Turn off Car Climate”. I don’t think this would work if you started your car directly (via ignition), though.

**Comment by samrum** [comment]
Closing this since it's already supported as far as I can tell.
One thing to note would be that your car doors have to be locked for remote start to work.
