### ISSUE TITLE
Requests not working

### ISSUE THREAD

**Issue by dangerusty** [samrum/homebridge-onstar#17]
For the past week or so, requests to start climate have not arrived to the car. Onstar works still via onstar app and Alexa. Is this a rotated key situation? Homebridge log only shows “start: requested”.

**Comment by samrum** [comment]
It's been working ok for me. Have you tried restarting homebridge?
Also make sure you have the latest version of the plugin. Pre-1.2.6 wouldn't log error messages in some cases.

**Comment by dangerusty** [comment]
Restart worked, sorry I should have tried that first. May schedule nightly
restarts.
