### ISSUE TITLE
[Car] start: Error: Request Failed with status 400 - Bad Request

### ISSUE THREAD

**Issue by deboy69** [samrum/homebridge-onstar#171]
Plugin isnt working. I receive an error with [Car] start: Error: Request Failed with status 400 - Bad Request

**Comment by samrum** [comment]
Is it with a specific action? 
Could try changing the device id you’re using and restart homebridge as referenced here: https://github.com/samrum/homebridge-onstar/issues/8

**Comment by deboy69** [comment]
Both starting and locking both generate the error. Tried changing the UUID and still gives the error.

**Comment by deboy69** [comment]
was running 1.5.9. Upgraded to 1.5.10 and have the same issue and error. Native GMC app runs just fine and works and it should.

**Comment by samrum** [comment]
Hmm, yeah, I don’t know. It’s been working fine for me, so I don’t think it’s an onstarjs app credential issue.

**Comment by deboy69** [comment]
I ended up just uninstalling and reinstall homebridge and the plugin. Ended up working again. So maybe a bad update  in my system files idk.

**Comment by Z1mDMan** [comment]
I'm seeing this right now.

**Comment by samrum** [comment]
@Z1mDMan I pushed an update with the latest credentials. Try that one. If it’s still an issue, probably open a new issue.
