### ISSUE TITLE
Canadian Onstar

### ISSUE THREAD

**Issue by simongirard93** [samrum/homebridge-onstar#2]
This plugin only work with American Onstar, is it possible to add Canadian compatibility ?

Thank you,

**Comment by samrum** [comment]
I'd need to see what API requests to Canadian OnStar look like.
Is there a mobile app that you can use to issue commands that different than the myChevrolet app?
This plugin is based off of API requests made using that app. The requests go to https://api.gm.com/api/v1 which doesn't seem like it would be US only, but there may be a different subdomain for other countries.

**Comment by simongirard93** [comment]
My mistake, everything is fine. Onstar use the same API for US and CAN it's just not the same authentification page when you try to connect directly on the web page. Your plugin works
Thank you,
