### ISSUE TITLE
start: Error: Request Failed with status 500 - Internal Server Error

### ISSUE THREAD

**Issue by adisor19** [samrum/homebridge-onstar#21]
I set up everything and I keep getting 

start: Error: Request Failed with status 500 - Internal Server Error

When attemting to start the car.. any ideas?

**Comment by ukypayne** [comment]
Post your config (redacted)

**Comment by adisor19** [comment]
"accessories": [
        {
            "name": "Volt",
            "deviceId": "eb902c27-xxxx-xxxx-xxxx-f8834aa0bf95",
            "vin": "xxxxxxxxxxxxxx-xx",
            "username": "user@gmail.com",
            "password": "password",
            "onStarPin": "xxxx",
            "enableAlert": false,
            "enableCharger": false,
            "enableDoors": false,
            "doorsDefaultToUnlocked": false,
            "accessory": "OnStar"
        }

**Comment by adisor19** [comment]
This is for a car in Canada.. in case that has anything to do with it. From the OnStar app, it works fine.

**Comment by samrum** [comment]
500 is an interesting error. Might be an issue with your configuration.
In your redacted config your VIN has a dash in it? I don’t think that’s valid.

**Comment by adisor19** [comment]
Oh wow.. you're right. Not sure how that dash got in there. I corrected it and it works fine.
