### ISSUE TITLE
status 401 - Unauthorized

### ISSUE THREAD

**Issue by luosuonan** [samrum/homebridge-onstar#22]
[2/7/2020, 4:17:21 PM] Homebridge is running on port 51520.
[2/7/2020, 4:17:25 PM] [Config] Homebridge Config UI X v4.10.0 is listening on :: port 8080
[2/7/2020, 4:17:48 PM] [CAR] unlockDoor: Requested
[2/7/2020, 4:18:20 PM] [CAR] unlockDoor: Error: Request Failed with status 401 - Unauthorized

**Comment by luosuonan** [comment]
signing_key = jwk.JWK(**{'k': base64.b64encode("OxeOjX9FnVkJQQdSuwvR"), 'kty':'oct'})
client_id = "OMB_CVY_AND_3P0"

need update?

**Comment by luosuonan** [comment]
CN onstar have Different interfaces

**Comment by samrum** [comment]
What do you mean by different interfaces? Different base API url? Different endpoints?

**Comment by luosuonan** [comment]
https://api.shanghaionstar.com
api url different from US
Can you help intercept it

**Comment by samrum** [comment]
Can you run through these steps to see if the only difference is the base url? 
1. Checkout https://github.com/samrum/OnStarJS/tree/region-zh-cn
1. Run `yarn install`
1. Copy .env.sample to .env
2. Replace the variables in .env with your credentials
3. Run `yarn test:functional`

If the tests pass, it means it works and I can add support for swapping regions to that library and this one.
