### ISSUE TITLE
Error trying to start

### ISSUE THREAD

**Issue by evilavenger35** [samrum/homebridge-onstar#246]
Hi, I started receiving an error the other day when trying to start, the message is : “the request failed with status, 403 - forbidden”. 

Let me know if you need anymore details. 

Thanks!!

**Comment by asvictory3** [comment]
I sometimes get this. A homebridge server restart usually fixes it.

**Comment by jianyu-li** [comment]
I'm getting the same for about a week

**Comment by jfmeuniercow** [comment]
me too. Same error: 403

**Comment by BennyDaBee** [comment]
Just posting this here. He is working on it with issue in OnStarJS https://github.com/samrum/OnStarJS/issues/208

**Comment by samrum** [comment]
Should be fixed now with [v1.5.20](https://github.com/samrum/homebridge-onstar/releases/tag/v1.5.20)

**Comment by jianyu-li** [comment]
> Should be fixed now with [v1.5.20](https://github.com/samrum/homebridge-onstar/releases/tag/v1.5.20)

Worked for me! Thanks!

**Comment by evilavenger35** [comment]
Thanks Ruben!! Sent from my iPhoneOn Nov 3, 2022, at 01:11, Ruben Medina ***@***.***> wrote:﻿
Should be fixed now with v1.5.20
