### ISSUE TITLE
Commands not getting thorough

### ISSUE THREAD

**Issue by evilavenger35** [samrum/homebridge-onstar#256]
Hi, I started receiving “Error: request failed with status 401 - unauthorized “, I think the token may have expired again. Please let me know if you need more information. 
Thanks,
Mike

**Comment by xcsdm** [comment]
Same here also.

Unfortunately, in a previous similar ticket the dev mentioned they no longer use OnStar.

> I don't have a way to test that it fixes the issue since I no longer have a Chevrolet, so if the way token management has changed or the authentication for certain commands is different, that's going to require more investigation to update.

**Comment by garyd9** [comment]
> Unfortunately, in a previous similar ticket the dev mentioned they no longer use OnStar.

Perhaps, but I do see that @samrum is still updating their OnStarJS repo, so perhaps they can update whatever is needed for this one.

**Comment by treyblair** [comment]
Same here as well. 
Really love this plug-in so hopeful that someone can fix it.

**Comment by usmcfiredog** [comment]
I am also experiencing this issue

1/8/2023, 11:12:37 AM Onstar Bridge unlockDoor: Requested
1/8/2023, 11:12:37 AM Onstar Bridge unlockDoor: Error: Request Failed with status 401 - Unauthorized

**Comment by jianyu-li** [comment]
Same here. Is there anything we can do to help provide the necessary information since the dev no longer uses onstar?

**Comment by Z1mDMan** [comment]
I'm also willing to help provide info/beta feedback for a fix. I wish I knew how to help more directly. I find this plugin very useful.

**Comment by BennyDaBee** [comment]
https://github.com/samrum/OnStarJS/issues/214

**Comment by Z1mDMan** [comment]
any update on this? how can I help (as a non-programmer but tech savvy)

**Comment by thetaz001** [comment]
Any updates on this? Ditto to above comments HOW CAN I HELP troubleshoot?
I am not a programmer either but am a network Engineer!
I'd he happy to help in any way i can TO GET THIS working again!
Please @AppDeveloper
let us know how we can help you revive this plugin!

**Comment by samrum** [comment]
Thanks to work by some lovely people over in OnStarJS, this should be working again with v1.5.22.

**Comment by johnsills1** [comment]
Samrum, thanks for getting this working again. You have just made a lot of people happy.

**Comment by mrwestside12** [comment]
This still isn't working for me?

**Comment by johnsills1** [comment]
You may have to reset your password and get a new UUID

**Comment by Archerdaddy** [comment]
Worked for me after uninstalling, reinstalling with new UUID. Not sure if it matters, but I disabled the newer 2FA code generating setting.

**Comment by mrwestside12** [comment]
Deleted and reinstalled and it fixed it.

**Comment by jmendoza22** [comment]
If you create a new UUID it will work again. They must be banning UUIDs some how

https://www.uuidgenerator.net/

**Comment by usmcfiredog** [comment]
updated the plugin and changed the UUIDs and still nothing here. Will investigate more when I get home from work

**Comment by jianyu-li** [comment]
Updated plugin, changed UUID and restarted homebridge. Worked for me. Thanks!

**Comment by treyblair** [comment]
Same for me. Thanks to any and everyone who helped get this going again.

**Comment by Z1mDMan** [comment]
confirming this is now fixed for me many thanks!!!

**Comment by asvictory3** [comment]
I’d like to thank the devs here and OnStarJS - we appreciate the work done to get this back up and running. I’m sure it was tedious but there are a lot of people who use this and couldn’t do the work on our own. 👍🏼

**Comment by ifeign** [comment]
The latest update appears to have fixed this. Just tested it

**Comment by thetaz001** [comment]
THANK YOU THANK YOU to ALL/WHOEVER had a hand in fixing this!! it is very much appreciated..

**Comment by usmcfiredog** [comment]
Uninstalled and reinstalled with new UUIDs and all is good now. Thank you all

**Comment by garyd9** [comment]
Should this be closed?
