### ISSUE TITLE
Request failed Status 400

### ISSUE THREAD

**Issue by iamsparks** [samrum/homebridge-onstar#262]
Any commands sent are now failing and the log is showing:

“Error: Request Failed with status 400 - Bad Request.” 

Any recommendations ?

**Comment by wbizreh** [comment]
I am having the same issue. Have you been able to find a solution? I tried everything from restarting HB, uninstalling and reinstalling( did that 3 times), changing deviceID but still having the same issue. I can send commands from the myChevrolet app without any issues

**Comment by billchilders** [comment]
Seeing the same issue here, too. This worked fine for months, then just broke a couple of days ago. Haven't been able to pin this down to a change on my side ...

**Comment by aquadan88** [comment]
Also same issue. Worked great since I purchased the vehicle and set the plugin up in January. Now I can't get it to work.

**Comment by pseudocultist** [comment]
Same here, guessing GM changed their API call structure, this has become a favorite plugin very quickly.

**Comment by johnynfulleffect** [comment]
Same issue here. 400’s in Homebridge.

**Comment by johnynfulleffect** [comment]
@samrum Same issue here. 400’s in Homebridge.
