### ISSUE TITLE
Lock and unlock

### ISSUE THREAD

**Issue by deboy69** [samrum/homebridge-onstar#29]
How does one get the lock and unlock features as seperate functions? So if i wanted to lock the doors at night or unlock them in the morning.

**Comment by ukypayne** [comment]
You record the scene with the setting you want. So you select the lock function for the scene, and then adjust it to lock/unlock depending on what you want the scene to do. The same way you would add a light, and then adjust the brightness.

**Comment by deboy69** [comment]
Thanks
