### ISSUE TITLE
After homebridge is started, I always get a 'door locked' message when I first visit/use homebridge

### ISSUE THREAD

**Issue by joberembt** [samrum/homebridge-onstar#36]
Whenever I restart Homebridge, if I visit the Accessories page via Config UI X, or open the Home app and go to the room the vehicle is part of, I get a 'ROOM Vehicle doors was locked' message with the ROOM and Vehicle filled out with the actual values.

**Comment by samrum** [comment]
I'm not sure there's anything I can do about that. It might just be how locks are handled by the OS. 

Are you restarting homebridge often? You could try enabling the **doorsDefaultToUnlocked** which would probably stop the notification on restart (but would default the toggle to unlocked).
