### ISSUE TITLE
Error 400

### ISSUE THREAD

**Issue by asvictory3** [samrum/homebridge-onstar#37]
I appreciate the work you've put into this project. Today I've been getting this error, which looks to be recurrent after reading your prior tickets.

lockDoor: Error: Request Failed with status 400 - Bad Request

I've updated my UUID and restarted home bridge service a few times without success. Maybe once again, they've rotated these secret keys?

**Comment by samrum** [comment]
Yeah, I’m aware of this and will work on an update later today.
Thanks for the report.

**Comment by samrum** [comment]
Latest release (1.4.1) fixes this.
