### ISSUE TITLE
error 400 - bad request

### ISSUE THREAD

**Issue by alexandrupaulpopa** [samrum/homebridge-onstar#4]
For about 1-2 days now it stoped working, getting error 400 - bad request any clue what that might be?

Thanks

Alex

**Comment by samrum** [comment]
Hi @alexandrupaulpopa,

Thanks for the report.
I've fixed this issue in the library that homebridge-onstar uses ([OnStarJS](https://www.npmjs.com/package/onstarjs)) and I'll be testing and releasing an update later today that will fix homebridge-onstar.

Thanks

**Comment by samrum** [comment]
This is fixed in v1.2.2.

What happened was the client id and/or secret that were being used for authorization were no longer valid so I updated those.

**Comment by Z1mDMan** [comment]
I'm seeing this today. Is this needing an update?

**Comment by BoostN** [comment]
I'm getting the same thing as well @Z1mDMan
