### ISSUE TITLE
Homebridge Verified Plugin

### ISSUE THREAD

**Issue by ifeign** [samrum/homebridge-onstar#40]
Your plugin should already meet the requirements to become Homebridge Verified, why not submit it?
https://github.com/homebridge/verified

**Comment by samrum** [comment]
Sure, I can submit it for verification. Seems like I would need to add some config checks when starting, but that's simple enough.

Thanks for the suggestion.

**Comment by samrum** [comment]
Submitted for review here: https://github.com/homebridge/verified/issues/243
