### ISSUE TITLE
Failing to start

### ISSUE THREAD

**Issue by Z1mDMan** [samrum/homebridge-onstar#47]
Seeing this lately and I see the OnStarJS recently updated. Is it possible the homebridge plug-in also needs a code update?

[37m[3/10/2021, 18:05:44] [39m[36m[Malibu][39m start: Requested

[37m[3/10/2021, 18:05:45] [39m[36m[Malibu][39m start: Error: Request Failed with status 400 - Bad Request

**Comment by samrum** [comment]
Oh, looks like I never published a new version the last time OnStarJS was updated. I just did now, thanks for the heads up. Should help with those, but let me know.

**Comment by Z1mDMan** [comment]
Thank you that did the trick!
