### ISSUE TITLE
Bad Request: Error 400

### ISSUE THREAD

**Issue by haydenssmith** [samrum/homebridge-onstar#50]
I set up the pluggin per the readme and I'm still getting Error 400. Any idea how to fix this? 

I appreciate all the work you've put into this!

**Comment by jmendoza22** [comment]
> I set up the pluggin per the readme and I'm still getting Error 400. Any idea how to fix this?
> 
> I appreciate all the work you've put into this!

I noticed this yesterday. It’s a new issue that just started happening.

**Comment by ukypayne** [comment]
Same issue, and I had everything working with my config.

**Comment by jmendoza22** [comment]
> Same issue, and I had everything working with my config.

I’m sure something changed server side but hopefully it can be updated soon.

**Comment by samrum** [comment]
Just app keys in OnStarJS out of date again 😐. I pushed a new release (1.5.2) that will work again.

Going to look more into automating these updates when new version of myChevrolet are published.

**Comment by deboy69** [comment]
Error is back
