### ISSUE TITLE
Error Code 500

### ISSUE THREAD

**Issue by bigjayman1** [samrum/homebridge-onstar#52]
I get an error code 500 Internal Server Response when I use this plugin.  Any suggestions?

**Comment by samrum** [comment]
In the past, that’s been reported when the configuration values are invalid (like improperly formatted VIN). So double check those and also check that you’re still able to make requests from the mobile app for your vehicle.

**Comment by bigjayman1** [comment]
Thank you so much! That worked. VIN is case sensitive.

**Comment by samrum** [comment]
Ah, interesting. I can add in some logic to uppercase VINs if that’s the case.

Glad it works for you now.
