### ISSUE TITLE
400: Bad Request

### ISSUE THREAD

**Issue by ukypayne** [samrum/homebridge-onstar#8]
After the 1.2.4 update, I have a "400 Bad Request" error when trying to use the start option.

**Comment by ukypayne** [comment]
Changing ID to any other number corrected issue.

**Comment by samrum** [comment]
Changing deviceId? It's possible you just needed to restart homebridge.

**Comment by ukypayne** [comment]
I tried relaunching and rebooting the device first. Once I changed the deviceID it worked again.

**Comment by samrum** [comment]
Interesting. Good to know, though, thanks.
